import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { withUser } from "@/lib/db";
import { apiError } from "@/lib/http";
import { assertSameOrigin, securityError } from "@/lib/security";

const ALLOWED = new Set(["image/jpeg","image/png","image/webp"]);
export async function GET() { const session=await getSession(); if(!session) return new NextResponse(null,{status:401}); const row=await withUser(session.id,async c=>(await c.query<{avatar_data:Buffer;avatar_mime:string}>("SELECT avatar_data,avatar_mime FROM app_user WHERE id=$1 AND avatar_data IS NOT NULL",[session.id])).rows[0]); if(!row) return new NextResponse(null,{status:404}); return new NextResponse(new Uint8Array(row.avatar_data),{headers:{"Content-Type":row.avatar_mime,"Cache-Control":"private, max-age=300","X-Content-Type-Options":"nosniff"}}); }
export async function POST(request:Request) { const session=await getSession(); if(!session) return NextResponse.json({error:"Não autenticado."},{status:401}); try { assertSameOrigin(request); const form=await request.formData(); const file=form.get("avatar"); if(!(file instanceof File)||!ALLOWED.has(file.type)||file.size>2_000_000) return NextResponse.json({error:"Envie JPG, PNG ou WebP de até 2 MB."},{status:422}); const bytes=Buffer.from(await file.arrayBuffer()); const valid=(file.type==="image/png"&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(file.type==="image/jpeg"&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[bytes.length-2]===0xff&&bytes[bytes.length-1]===0xd9)||(file.type==="image/webp"&&bytes.subarray(0,4).toString()==="RIFF"&&bytes.subarray(8,12).toString()==="WEBP"); if(!valid) return NextResponse.json({error:"O conteúdo do arquivo não corresponde a uma imagem válida."},{status:422}); await withUser(session.id,c=>c.query("UPDATE app_user SET avatar_data=$1,avatar_mime=$2,updated_at=now() WHERE id=$3",[bytes,file.type,session.id])); return NextResponse.json({ok:true}); } catch(e){return securityError(e)??apiError(e);} }
