"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Eye, EyeOff, ShieldCheck, TrendingUp } from "lucide-react";
function Logo(){return <div className="logo auth-logo"><span className="logo-mark"><i/><i/><i/></span><span>Smart<strong>Banca</strong></span></div>}
export function AuthForm(){
  const router=useRouter(); const [mode,setMode]=useState<"login"|"register">("login"); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const payload=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok){setError(body.error??"Não foi possível continuar.");setLoading(false);return;}router.push("/");router.refresh();}
  return <main className="auth-page"><section className="auth-stage"><Logo/><div className="auth-copy"><div className="score-stamp"><TrendingUp size={18}/><span>Gestão que joga a seu favor</span></div><h1>Clareza para apostar.<br/>Disciplina para crescer.</h1><p>Separe capital, lucro e risco. Cada ticket entra na conta, do depósito ao cashout.</p></div><div className="auth-score"><div><span>Banca</span><strong>100%</strong><small>sob seu controle</small></div><i/><div><span>Dados</span><strong>RLS</strong><small>isolados por conta</small></div></div></section><section className="auth-card"><div className="auth-card-inner"><div className="auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>{setMode("login");setError("");}}>Entrar</button><button className={mode==="register"?"active":""} onClick={()=>{setMode("register");setError("");}}>Criar conta</button></div><div className="auth-heading"><h2>{mode==="login"?"Bem-vindo de volta":"Comece com a banca zerada"}</h2><p>{mode==="login"?"Acesse seu painel financeiro.":"Seus dados começam limpos e só você tem acesso."}</p></div><form onSubmit={submit}>{mode==="register"?<label>Seu nome<input name="name" required minLength={2} maxLength={80} autoComplete="name" placeholder="Como devemos chamar você?"/></label>:null}<label>E-mail<input name="email" required type="email" autoComplete="email" placeholder="voce@exemplo.com"/></label><label>Senha<div className="password-field"><input name="password" required minLength={mode==="register"?12:1} maxLength={128} type={show?"text":"password"} autoComplete={mode==="login"?"current-password":"new-password"} placeholder={mode==="register"?"12+ caracteres, maiúscula e número":"Sua senha"}/><button type="button" aria-label={show?"Ocultar senha":"Mostrar senha"} onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{mode==="login"?<Link className="forgot-link" href="/recuperar">Esqueci minha senha</Link>:null}{error?<p className="auth-error" role="alert">{error}</p>:null}<button className="primary-button auth-submit" disabled={loading}>{loading?"Aguarde…":mode==="login"?"Entrar na minha banca":"Criar minha conta"}</button></form><p className="auth-security"><ShieldCheck size={15}/> Senha protegida com bcrypt e sessão segura.</p></div></section></main>;
}
