"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Eye, EyeOff, ShieldCheck, TrendingUp } from "lucide-react";
function Logo(){return <div className="logo auth-logo"><span className="logo-mark"><i/><i/><i/></span><span>Smart<strong>Banca</strong></span></div>}
export function AuthForm(){
  const router=useRouter(); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const payload=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok){setError(body.error??"Não foi possível continuar.");setLoading(false);return;}router.push(body.role==="admin"?"/admin":"/");router.refresh();}
  return <main className="auth-page"><section className="auth-stage"><Logo/><div className="auth-copy"><div className="score-stamp"><TrendingUp size={18}/><span>Gestão que joga a seu favor</span></div><h1>Clareza para apostar.<br/>Disciplina para crescer.</h1><p>Separe capital, lucro e risco. Cada ticket entra na conta, do depósito ao cashout.</p></div><div className="auth-score"><div><span>Banca</span><strong>100%</strong><small>sob seu controle</small></div><i/><div><span>Dados</span><strong>RLS</strong><small>isolados por conta</small></div></div></section><section className="auth-card"><div className="auth-card-inner"><div className="auth-access-label"><ShieldCheck size={17} aria-hidden="true"/>Acesso exclusivo para clientes</div><div className="auth-heading"><h2>Bem-vindo de volta</h2><p>Entre com os dados enviados pelo SmartBanca.</p></div><form onSubmit={submit}><label>E-mail<input name="email" required type="email" autoComplete="email" spellCheck={false} placeholder="voce@exemplo.com"/></label><label>Senha<div className="password-field"><input name="password" required maxLength={128} type={show?"text":"password"} autoComplete="current-password" placeholder="Sua senha"/><button type="button" aria-label={show?"Ocultar senha":"Mostrar senha"} onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><Link className="forgot-link" href="/recuperar">Esqueci minha senha</Link>{error?<p className="auth-error" role="alert">{error}</p>:null}<button className="primary-button auth-submit" disabled={loading}>{loading?"Aguarde…":"Entrar na minha banca"}</button></form><p className="auth-security"><ShieldCheck size={15}/> Senha protegida com bcrypt e sessão segura.</p></div></section></main>;
}
