"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { calculateBank } from "@/lib/finance";
import { BankEvolution } from "@/components/bank-evolution";
import { ArrowDownLeft, ArrowUpRight, BarChart3, Bell, Camera, ChevronDown, CircleDollarSign, Download, LayoutDashboard, LogOut, Menu, Pencil, Plus, ReceiptText, Search, Settings2, Target, Trash2, TrendingUp, Wallet, X } from "lucide-react";

type Bet = { id: string; sport: string; event: string; date: string; placedAt: string; settledAt: string | null; stake: number; odd: number; status: "Green" | "Red" | "Pendente" | "Cashout" | "Anulada"; result: number };
type Transaction = { id: string; type: "Depósito" | "Saque"; amount: number; date: string; occurredAt: string; note: string };
type LocalData = { bets: Bet[]; transactions: Transaction[] };
type UserProfile = { name: string; email: string; hasAvatar: boolean };
const navItems = [{ icon: LayoutDashboard, label: "Visão geral", target: "overview" }, { icon: ReceiptText, label: "Apostas", target: "bets" }, { icon: Wallet, label: "Movimentações", target: "transactions" }, { icon: BarChart3, label: "Relatórios", target: "reports" }];

const defaultData: LocalData = { bets: [], transactions: [] };
function fromApi(bets: Record<string, unknown>[], transactions: Record<string, unknown>[]): LocalData {
  const statusMap: Record<string, Bet["status"]> = { pending: "Pendente", green_total: "Green", green_partial: "Green", red_total: "Red", red_partial: "Cashout", void: "Anulada" };
  return {
    bets: bets.map(row => ({ id: String(row.id), sport: String(row.sport), event: String(row.event_market ?? "Aposta sem descrição"), date: new Date(String(row.placed_at)).toLocaleString("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }), placedAt: String(row.placed_at), settledAt: row.settled_at ? String(row.settled_at) : null, stake: Number(row.stake), odd: Number(row.initial_odd), status: statusMap[String(row.status)] ?? "Pendente", result: String(row.status) === "pending" ? Number(row.potential_return) : Number(row.effective_return) - Number(row.stake) })),
    transactions: transactions.map(row => ({ id: String(row.id), type: String(row.type) === "deposit" ? "Depósito" : "Saque", amount: Number(row.amount), date: new Date(String(row.occurred_at)).toLocaleString("pt-BR"), occurredAt: String(row.occurred_at), note: String(row.note ?? "") }))
  };
}

function useBank() {
  const router = useRouter();
  const [data, setData] = useState<LocalData>({ bets: [], transactions: [] });
  const [ready, setReady] = useState(false);
  useEffect(() => { let active = true; async function load() { const responses = await Promise.all([fetch("/api/bets"), fetch("/api/transactions")]); if (responses.some(r => r.status === 401)) { router.replace("/login"); return; } if (!responses.every(r => r.ok)) throw new Error("Não foi possível carregar a banca."); const [bets, transactions] = await Promise.all(responses.map(r => r.json())); if (active) setData(fromApi(bets, transactions)); } load().catch(() => { if (active) setData(defaultData); }).finally(() => { if (active) setReady(true); }); return () => { active = false; }; }, [router]);
  return [data, setData, ready] as const;
}
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

function Logo() { return <div className="logo"><span className="logo-mark"><i /><i /><i /></span><span>Smart<strong>Banca</strong></span></div>; }

function initials(name:string){return name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase();}
function Nav({user,onProfile}:{user:UserProfile;onProfile:()=>void}) {
  return <aside className="sidebar"><Logo /><nav>{navItems.map(({ icon: Icon, label, target },index) => <button className={index===0 ? "active" : ""} onClick={() => document.getElementById(target)?.scrollIntoView({ behavior: "smooth" })} key={label}><Icon size={19} /><span>{label}</span>{index===0 ? <b /> : null}</button>)}</nav><div className="sidebar-bottom"><button onClick={onProfile}><Settings2 size={19} /><span>Meu perfil</span></button><button className="profile" onClick={onProfile}>{user.hasAvatar?<Image unoptimized width={34} height={34} src={`/api/profile/avatar?v=${encodeURIComponent(user.name)}`} alt=""/>:<div className="avatar">{initials(user.name)}</div>}<div><strong>{user.name}</strong><span>{user.email}</span></div><ChevronDown size={16} /></button></div></aside>;
}

function Metric({ label, value, trend, icon: Icon, negative = false }: { label: string; value: string; trend: string; icon: typeof Wallet; negative?: boolean }) {
  return <article className="metric"><div className="metric-top"><span>{label}</span><Icon size={18} /></div><strong>{value}</strong><small className={negative ? "negative" : "positive"}>{trend}</small></article>;
}

function AddBetModal({ close, save }: { close: () => void; save: (bet: Bet) => void }) {
  const [stake, setStake] = useState("250"); const [odd, setOdd] = useState("1.85");
  const [sport, setSport] = useState("Futebol"); const [event, setEvent] = useState("");
  const potential = (Number(stake.replace(",", ".")) || 0) * (Number(odd.replace(",", ".")) || 0);
  return <div className="modal-backdrop" role="presentation" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><div><h2 id="modal-title">Registrar aposta</h2><p>A stake ficará retida até o encerramento.</p></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={20} /></button></header><form onSubmit={e => { e.preventDefault(); save({ id: crypto.randomUUID(), sport, event, date: "Agora", placedAt:new Date().toISOString(), settledAt:null, stake: Number(stake.replace(",", ".")), odd: Number(odd.replace(",", ".")), status: "Pendente", result: potential }); }}><label>Modalidade<select value={sport} onChange={e => setSport(e.target.value)}><option>Futebol</option><option>Basquete</option><option>Tênis</option><option>Vôlei</option><option>eSports</option></select></label><label className="full">Evento e mercado<input required maxLength={160} value={event} onChange={e => setEvent(e.target.value)} placeholder="Ex.: Flamengo × Palmeiras · Mais de 2,5 gols" /></label><label>Valor da entrada<div className="input-prefix"><span>R$</span><input required min="0.01" type="number" step="0.01" inputMode="decimal" value={stake} onChange={e => setStake(e.target.value)} /></div></label><label>Odd inicial<input required min="1.01" type="number" step="0.01" inputMode="decimal" value={odd} onChange={e => setOdd(e.target.value)} /></label><div className="potential full"><span>Retorno potencial</span><strong>{money.format(potential)}</strong></div><div className="form-actions full"><button type="button" className="ghost-button" onClick={close}>Cancelar</button><button className="primary-button" type="submit">Salvar aposta</button></div></form></section></div>;
}

function TransactionModal({ type, close, save }: { type: "Depósito" | "Saque"; close: () => void; save: (transaction: Transaction) => void }) {
  const [amount, setAmount] = useState(""); const [note, setNote] = useState("");
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><section className="modal compact-modal" role="dialog" aria-modal="true"><header><div><h2>Registrar {type.toLowerCase()}</h2><p>{type === "Depósito" ? "O valor será somado ao capital próprio." : "O valor será retirado do saldo disponível."}</p></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={20} /></button></header><form onSubmit={e => { e.preventDefault(); save({ id: crypto.randomUUID(), type, amount: Number(amount.replace(",", ".")), note, date: "Agora", occurredAt:new Date().toISOString() }); }}><label className="full">Valor<div className="input-prefix"><span>R$</span><input autoFocus required min="0.01" type="number" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></div></label><label className="full">Descrição<input maxLength={200} value={note} onChange={e => setNote(e.target.value)} placeholder="Opcional" /></label><div className="form-actions full"><button type="button" className="ghost-button" onClick={close}>Cancelar</button><button className="primary-button" type="submit">Registrar</button></div></form></section></div>;
}

function SettleModal({ bet, close, save }: { bet: Bet; close: () => void; save: (status: Bet["status"], returned: number) => void }) {
  const [kind, setKind] = useState<"green_total" | "cashout" | "red_total" | "void">("green_total"); const [returned, setReturned] = useState(String(bet.stake));
  const effective = kind === "green_total" ? bet.stake * bet.odd : kind === "red_total" ? 0 : kind === "void" ? bet.stake : Number(returned.replace(",", "."));
  return <div className="modal-backdrop"><section className="modal compact-modal"><header><div><h2>Encerrar aposta</h2><p>{bet.event}</p></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={20} /></button></header><form onSubmit={e => { e.preventDefault(); const status: Bet["status"] = kind === "green_total" ? "Green" : kind === "red_total" ? "Red" : kind === "void" ? "Anulada" : "Cashout"; save(status, effective); }}><label className="full">Resultado<select value={kind} onChange={e => setKind(e.target.value as typeof kind)}><option value="green_total">Green total</option><option value="cashout">Cashout parcial</option><option value="red_total">Red total</option><option value="void">Anulada / void</option></select></label>{kind === "cashout" ? <label className="full">Valor efetivamente retornado<input required min="0.01" max={bet.stake * bet.odd - 0.01} type="number" step="0.01" value={returned} onChange={e => setReturned(e.target.value)} /></label> : null}<div className="potential full"><span>Retorno</span><strong>{money.format(effective)}</strong></div><div className="form-actions full"><button type="button" className="ghost-button" onClick={close}>Cancelar</button><button className="primary-button">Confirmar encerramento</button></div></form></section></div>;
}

function ProfileModal({user,close,update}:{user:UserProfile;close:()=>void;update:(user:UserProfile)=>void}){const router=useRouter();const[name,setName]=useState(user.name);const[busy,setBusy]=useState(false);const[avatarPreview,setAvatarPreview]=useState(user.hasAvatar?"/api/profile/avatar":"");async function save(e:React.FormEvent){e.preventDefault();setBusy(true);const response=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});if(response.ok){const body=await response.json();update({name:body.name,email:body.email,hasAvatar:body.has_avatar});close();}setBusy(false);}async function upload(file?:File){if(!file)return;if(file.size>2_000_000){alert("A imagem deve ter no máximo 2 MB.");return;}const form=new FormData();form.append("avatar",file);setBusy(true);const response=await fetch("/api/profile/avatar",{method:"POST",body:form});if(response.ok){setAvatarPreview(URL.createObjectURL(file));update({...user,hasAvatar:true});}setBusy(false);}async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/login");router.refresh();}return <div className="modal-backdrop"><section className="modal compact-modal profile-modal"><header><div><h2>Meu perfil</h2><p>Personalize como você aparece no SmartBanca.</p></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={20}/></button></header><form onSubmit={save}><div className="profile-photo full">{avatarPreview?<Image unoptimized width={76} height={76} src={avatarPreview} alt="Foto do perfil"/>:<div>{initials(name||user.name)}</div>}<label className="ghost-button"><Camera size={16}/>Trocar foto<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label><small>JPG, PNG ou WebP · até 2 MB</small></div><label className="full">Nome<input value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={80}/></label><label className="full">E-mail<input value={user.email} disabled/></label><div className="profile-actions full"><button type="button" className="logout-button" onClick={logout}><LogOut size={16}/>Sair da conta</button><button className="primary-button" disabled={busy}>{busy?"Salvando…":"Salvar perfil"}</button></div></form></section></div>}

export function Dashboard({initialUser}:{initialUser:UserProfile}) {
  const [data, setData, ready] = useBank();
  const [user,setUser]=useState(initialUser); const [profileOpen,setProfileOpen]=useState(false);
  const [period, setPeriod] = useState("Mês atual"); const [customStart,setCustomStart]=useState(""); const [customEnd,setCustomEnd]=useState(""); const [referenceNow]=useState(()=>new Date()); const [modal, setModal] = useState(false); const [mobile, setMobile] = useState(false);
  const [transactionType, setTransactionType] = useState<"Depósito" | "Saque" | null>(null); const [settling, setSettling] = useState<Bet | null>(null); const [query, setQuery] = useState(""); const [toast, setToast] = useState("");
  const [cookieChoice,setCookieChoice]=useState<string|null>(null);
  useEffect(()=>{queueMicrotask(()=>setCookieChoice(localStorage.getItem("smartbanca-cookie-consent")));},[]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase("pt-BR"); return needle ? data.bets.filter(b => `${b.event} ${b.sport} ${b.status}`.toLocaleLowerCase("pt-BR").includes(needle)) : data.bets; }, [data.bets, query]);
  const metrics = useMemo(() => {
    const bank=calculateBank(data.bets.map(b=>({stake:b.stake,result:b.result,pending:b.status==="Pendente"})),data.transactions.map(t=>({type:t.type==="Depósito"?"deposit" as const:"withdrawal" as const,amount:t.amount})));
    const {deposits,withdrawals,held,profit}=bank;
    const settled = data.bets.filter(b => b.status !== "Pendente"); const wins = settled.filter(b => b.result > 0).length;
    const greenValue=data.bets.filter(b=>b.status==="Green").reduce((sum,b)=>sum+Math.max(0,b.result),0);
    const redValue=Math.abs(data.bets.filter(b=>b.status==="Red").reduce((sum,b)=>sum+Math.min(0,b.result),0));
    return { deposits, withdrawals, held, profit, greenValue, redValue, total: bank.available, roi: deposits ? profit / deposits * 100 : 0, winRate: settled.length ? wins / settled.length * 100 : 0 };
  }, [data]);
  const periodReport = useMemo(() => {
    const end = period === "Intervalo personalizado" && customEnd ? new Date(`${customEnd}T23:59:59`) : referenceNow;
    let start: Date;
    if (period === "Semana atual") { start=new Date(referenceNow); const day=(start.getDay()+6)%7; start.setDate(start.getDate()-day); start.setHours(0,0,0,0); }
    else if (period === "Mês atual") start=new Date(referenceNow.getFullYear(),referenceNow.getMonth(),1);
    else if (period === "Últimos 30 dias") { start=new Date(referenceNow); start.setDate(start.getDate()-29); start.setHours(0,0,0,0); }
    else start=customStart?new Date(`${customStart}T00:00:00`):new Date(0);
    const placed=data.bets.filter(b=>{const date=new Date(b.placedAt);return date>=start&&date<=end;});
    const settled=data.bets.filter(b=>b.settledAt&&new Date(b.settledAt)>=start&&new Date(b.settledAt)<=end);
    const movements=data.transactions.filter(t=>{const date=new Date(t.occurredAt);return date>=start&&date<=end;});
    const stake=placed.reduce((sum,b)=>sum+b.stake,0); const profit=settled.reduce((sum,b)=>sum+b.result,0);
    const greenBets=settled.filter(b=>b.status==="Green"); const redBets=settled.filter(b=>b.status==="Red");
    const greens=greenBets.length; const reds=redBets.length; const greenValue=greenBets.reduce((sum,b)=>sum+Math.max(0,b.result),0); const redValue=Math.abs(redBets.reduce((sum,b)=>sum+Math.min(0,b.result),0)); const voids=settled.filter(b=>b.status==="Anulada").length; const cashouts=settled.filter(b=>b.status==="Cashout").length;
    const deposits=movements.filter(t=>t.type==="Depósito").reduce((sum,t)=>sum+t.amount,0); const withdrawals=movements.filter(t=>t.type==="Saque").reduce((sum,t)=>sum+t.amount,0);
    const duration=end.getTime()-start.getTime(); const previousEnd=new Date(start.getTime()-1); const previousStart=new Date(previousEnd.getTime()-duration);
    const previousProfit=data.bets.filter(b=>b.settledAt&&new Date(b.settledAt)>=previousStart&&new Date(b.settledAt)<=previousEnd).reduce((sum,b)=>sum+b.result,0);
    const sportStats=["Futebol","Tênis","Basquete"].map(sport=>{const sportPlaced=placed.filter(b=>b.sport===sport);const volume=sportPlaced.reduce((sum,b)=>sum+b.stake,0);const sportProfit=settled.filter(b=>b.sport===sport).reduce((sum,b)=>sum+b.result,0);return {sport,tickets:sportPlaced.length,volume,profit:sportProfit};});
    const decided=greens+reds; const yieldRate=stake?profit/stake*100:0; const roi=deposits?profit/deposits*100:yieldRate; return {stake,profit,previousProfit,greens,reds,greenValue,redValue,voids,cashouts,deposits,withdrawals,roi,yieldRate,winRate:decided?greens/decided*100:0,bankChange:deposits-withdrawals+profit,oddAverage:placed.length?placed.reduce((sum,b)=>sum+b.odd,0)/placed.length:0,tickets:placed.length,sportStats,range:`${start.toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})} – ${end.toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})}`};
  },[data,period,customStart,customEnd,referenceNow]);
  const heldPercent = metrics.total + metrics.held > 0 ? Math.min(100, metrics.held / (metrics.total + metrics.held) * 100) : 0;
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2600); }
  function navigateTo(target:string){setMobile(false);requestAnimationFrame(()=>document.getElementById(target)?.scrollIntoView({behavior:"smooth",block:"start"}));}
  async function addBet(bet: Bet) { const response = await fetch("/api/bets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ placedAt: new Date().toISOString(), sport: bet.sport, eventMarket: bet.event, stake: bet.stake, initialOdd: bet.odd }) }); if (!response.ok) { notify("Não foi possível registrar a aposta."); return; } const saved = fromApi([await response.json()], []).bets[0]; setData(current => ({ ...current, bets: [saved, ...current.bets] })); setModal(false); notify("Aposta salva no PostgreSQL."); }
  async function addTransaction(transaction: Transaction) { if (transaction.type === "Saque" && transaction.amount > metrics.total) { notify("Saldo insuficiente para esse saque."); return; } const response = await fetch("/api/transactions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: transaction.type === "Depósito" ? "deposit" : "withdrawal", amount: transaction.amount, note: transaction.note }) }); if (!response.ok) { notify("Não foi possível registrar a movimentação."); return; } const saved = fromApi([], [await response.json()]).transactions[0]; setData(current => ({ ...current, transactions: [saved, ...current.transactions] })); setTransactionType(null); notify(`${transaction.type} salvo no PostgreSQL.`); }
  async function settleBet(status: Bet["status"], returned: number) { if (!settling) return; const dbStatus = status === "Green" ? (returned >= settling.stake * settling.odd ? "green_total" : "green_partial") : status === "Red" ? "red_total" : status === "Anulada" ? "void" : returned < settling.stake ? "red_partial" : "green_partial"; const response = await fetch(`/api/bets/${settling.id}/settle`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: dbStatus, effectiveReturn: returned }) }); if (!response.ok) { notify("Não foi possível encerrar a aposta."); return; } const settledAt=new Date().toISOString(); setData(current => ({ ...current, bets: current.bets.map(b => b.id === settling.id ? { ...b, status, result: returned - b.stake, settledAt } : b) })); setSettling(null); notify("Aposta encerrada no PostgreSQL."); }
  async function deleteBet(bet:Bet){if(!confirm(`Excluir a aposta “${bet.event}”?`))return;const response=await fetch(`/api/bets/${bet.id}`,{method:"DELETE"});if(!response.ok)return notify("Só apostas pendentes podem ser excluídas.");setData(current=>({...current,bets:current.bets.filter(item=>item.id!==bet.id)}));notify("Aposta excluída.");}
  async function deleteTransaction(transaction:Transaction){if(!confirm(`Excluir ${transaction.type.toLowerCase()} de ${money.format(transaction.amount)}?`))return;const response=await fetch(`/api/transactions/${transaction.id}`,{method:"DELETE"});if(!response.ok)return notify("Não foi possível excluir.");setData(current=>({...current,transactions:current.transactions.filter(item=>item.id!==transaction.id)}));notify("Movimentação excluída.");}
  async function editTransaction(transaction:Transaction){const value=prompt("Novo valor",String(transaction.amount).replace(".",","));if(value===null)return;const note=prompt("Descrição",transaction.note);if(note===null)return;const amount=Number(value.replace(",","."));if(!Number.isFinite(amount)||amount<=0)return notify("Informe um valor válido.");const response=await fetch(`/api/transactions/${transaction.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount,note})});if(!response.ok)return notify("Não foi possível editar.");setData(current=>({...current,transactions:current.transactions.map(item=>item.id===transaction.id?{...item,amount,note}:item)}));notify("Movimentação atualizada.");}
  function saveCookieChoice(value:string){localStorage.setItem("smartbanca-cookie-consent",value);setCookieChoice(value);notify("Preferências de cookies salvas.");}
  if (!ready) return <main className="loading-screen"><Logo /><p>Carregando sua banca…</p></main>;
  return <div className="app-shell">
    <Nav user={user} onProfile={()=>setProfileOpen(true)} />
    <main className="main">
      <header className="topbar"><button className="mobile-menu" aria-label={mobile?"Fechar menu":"Abrir menu"} aria-expanded={mobile} aria-controls="mobile-navigation" onClick={() => setMobile(v => !v)}>{mobile?<X size={22}/>:<Menu size={22} />}</button><div className="search"><Search size={18} /><input aria-label="Buscar" value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar aposta, evento ou modalidade" /></div><button className="notification" aria-label="Notificações" onClick={() => notify("Você não tem novas notificações.")}><Bell size={19} /></button><button className="primary-button" onClick={() => setModal(true)}><Plus size={18} />Nova aposta</button></header>
      {mobile ? <><button className="mobile-panel-backdrop" aria-label="Fechar menu" onClick={()=>setMobile(false)}/><nav className="mobile-panel" id="mobile-navigation" aria-label="Navegação principal"><Logo /><div className="mobile-profile"><button onClick={()=>{setMobile(false);setProfileOpen(true)}}>{user.hasAvatar?<Image unoptimized width={42} height={42} src={`/api/profile/avatar?v=${encodeURIComponent(user.name)}`} alt="Foto do perfil"/>:<span className="avatar">{initials(user.name)}</span>}<span><strong>{user.name}</strong><small>{user.email}</small></span><Settings2 size={18}/></button></div>{navItems.map(({icon:Icon,label,target})=><button className="mobile-nav-item" key={target} onClick={()=>navigateTo(target)}><Icon size={19}/><span>{label}</span></button>)}</nav></> : null}
      <div className="content">
        <section className="welcome"><div><p>Olá, {user.name.split(" ")[0]}</p><h1>Seu jogo, sob controle.</h1></div><div className="period-control"><select aria-label="Período" value={period} onChange={e => setPeriod(e.target.value)}><option>Semana atual</option><option>Mês atual</option><option>Últimos 30 dias</option><option>Intervalo personalizado</option></select>{period==="Intervalo personalizado"?<div className="custom-dates"><label>De<input type="date" value={customStart} onChange={e=>setCustomStart(e.target.value)}/></label><label>Até<input type="date" value={customEnd} onChange={e=>setCustomEnd(e.target.value)}/></label></div>:null}</div></section>
        <section className="period-report"><div className="period-report-heading"><div><span>Resultado do período</span><strong>{period}</strong></div><small>{periodReport.range}</small></div><div className="period-kpis"><div className="period-main"><span>Lucro / prejuízo</span><strong className={periodReport.profit>=0?"positive":"negative"}>{periodReport.profit>=0?"+ ":"− "}{money.format(Math.abs(periodReport.profit))}</strong><small>{periodReport.yieldRate.toFixed(1).replace(".",",")}% Yield · {periodReport.profit-periodReport.previousProfit>=0?"+ ":"− "}{money.format(Math.abs(periodReport.profit-periodReport.previousProfit))} vs. período anterior</small></div><div><span>Ganhos nos greens</span><strong className="positive">+ {money.format(periodReport.greenValue)}</strong><small>{periodReport.greens} {periodReport.greens===1?"green":"greens"} · {periodReport.winRate.toFixed(0)}% de acerto</small></div><div><span>Perdas nos reds</span><strong className="negative">− {money.format(periodReport.redValue)}</strong><small>{periodReport.reds} {periodReport.reds===1?"red":"reds"} · {periodReport.voids} anuladas</small></div><div><span>Cashouts</span><strong>{periodReport.cashouts}</strong><small>parciais no período</small></div><div><span>Volume apostado</span><strong>{money.format(periodReport.stake)}</strong><small>total de entradas</small></div><div><span>Variação da banca</span><strong className={periodReport.bankChange>=0?"positive":"negative"}>{periodReport.bankChange>=0?"+ ":"− "}{money.format(Math.abs(periodReport.bankChange))}</strong><small>inclui depósitos e saques</small></div></div></section>
        <BankEvolution bets={data.bets} transactions={data.transactions}/>
        <section id="overview" className="scoreboard"><div className="balance"><span>Banca total atual</span><strong>{money.format(metrics.total)}</strong><p><TrendingUp size={15} /> {metrics.roi.toFixed(1).replace(".", ",")}% <span>de retorno sobre depósitos</span></p></div><div className="score-grid"><Metric label="Capital próprio" value={money.format(metrics.deposits - metrics.withdrawals)} trend={`${data.transactions.length} movimentações`} icon={CircleDollarSign} /><Metric label="Lucro / prejuízo" value={`${metrics.profit>=0?"+ ":"− "}${money.format(Math.abs(metrics.profit))}`} trend="resultado líquido" icon={ArrowUpRight} negative={metrics.profit < 0} /><Metric label="Ganhos em greens" value={`+ ${money.format(metrics.greenValue)}`} trend="lucro bruto realizado" icon={TrendingUp} /><Metric label="Perdas em reds" value={`− ${money.format(metrics.redValue)}`} trend="prejuízo bruto realizado" icon={ArrowDownLeft} negative /><Metric label="Em apostas" value={money.format(metrics.held)} trend={`${data.bets.filter(b => b.status === "Pendente").length} tickets pendentes`} icon={Target} /></div></section>
        <section id="reports" className="chart-row"><article className="panel bank-breakdown"><div className="panel-heading"><div><h2>Como seu saldo foi formado</h2><p>Uma conta simples com tudo o que entrou e saiu</p></div></div><div className="bank-equation"><div><span>Você depositou</span><strong>{money.format(metrics.deposits)}</strong><small>Dinheiro colocado na banca</small></div><b>−</b><div><span>Você sacou</span><strong>{money.format(metrics.withdrawals)}</strong><small>Dinheiro retirado</small></div><b>{metrics.profit >= 0 ? "+" : "−"}</b><div><span>Resultado das apostas</span><strong className={metrics.profit >= 0 ? "positive" : "negative"}>{money.format(Math.abs(metrics.profit))}</strong><small>Lucros menos prejuízos</small></div><b>−</b><div><span>Ainda em jogo</span><strong>{money.format(metrics.held)}</strong><small>Apostas não encerradas</small></div><b>=</b><div className="equation-total"><span>Disponível agora</span><strong>{money.format(metrics.total)}</strong><small>Saldo livre para usar</small></div></div><div className="bank-explanation"><div className="availability-bar"><i style={{width:`${100-heldPercent}%`}}/><em style={{width:`${heldPercent}%`}}/></div><div className="availability-legend"><span><i/>Disponível: {money.format(metrics.total)}</span><span><i/>Em apostas: {money.format(metrics.held)}</span></div><p>{metrics.deposits === 0 ? "Comece registrando seu primeiro depósito. O painel fará as contas automaticamente." : metrics.held > 0 ? `${money.format(metrics.held)} está temporariamente em apostas. Ao encerrar os tickets, esse valor será atualizado.` : metrics.profit > 0 ? `Suas apostas já acrescentaram ${money.format(metrics.profit)} à sua banca.` : metrics.profit < 0 ? `O resultado das apostas reduziu a banca em ${money.format(Math.abs(metrics.profit))}.` : "Todo o seu saldo está disponível. Não há apostas pendentes neste momento."}</p></div></article>
          <article className="panel performance"><div className="panel-heading"><div><h2>Performance no período</h2><p>{periodReport.range}</p></div></div><div className="performance-grid"><div><span>ROI</span><strong>{periodReport.roi.toFixed(1).replace(".", ",")}%</strong><small className={periodReport.roi >= 0 ? "positive" : "negative"}>resultado real</small></div><div><span>Volume</span><strong>{money.format(periodReport.stake)}</strong><small>{periodReport.tickets} tickets</small></div><div><span>Win rate</span><strong>{periodReport.winRate.toFixed(0)}%</strong><small>apostas decididas</small></div><div><span>Odd média</span><strong>{periodReport.oddAverage.toFixed(2).replace(".", ",")}</strong><small>entradas do período</small></div></div><div className="sport-bars">{periodReport.sportStats.map(item=><div key={item.sport}><p><span>{item.sport} · {item.tickets} tickets</span><b className={item.profit>=0?"positive":"negative"}>{money.format(item.volume)} · {item.profit>=0?"+ ":"− "}{money.format(Math.abs(item.profit))}</b></p><i><em style={{width:`${periodReport.stake?item.volume/periodReport.stake*100:0}%`}}/></i></div>)}</div></article></section>
        <section id="transactions" className="quick-actions"><button onClick={() => setTransactionType("Depósito")}><span className="deposit"><ArrowDownLeft size={18} /></span><div><strong>Registrar depósito</strong><small>Adicionar capital próprio</small></div></button><button onClick={() => setTransactionType("Saque")}><span className="withdraw"><ArrowUpRight size={18} /></span><div><strong>Registrar saque</strong><small>Retirar saldo da banca</small></div></button></section>
        <section className="panel history-panel"><div className="panel-heading"><div><h2>Movimentações recentes</h2><p>Revise, corrija ou exclua lançamentos</p></div><div className="export-actions"><a className="ghost-button" href="/api/export/csv"><Download size={15}/>CSV</a><a className="ghost-button" href="/api/export/pdf" target="_blank"><Download size={15}/>PDF</a></div></div><div className="transaction-list">{data.transactions.slice(0,10).map(transaction=><div key={transaction.id}><span className={transaction.type==="Depósito"?"deposit-icon":"withdraw-icon"}>{transaction.type==="Depósito"?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</span><div><strong>{transaction.note||transaction.type}</strong><small>{transaction.type} · {transaction.date}</small></div><b className={transaction.type==="Depósito"?"positive":"negative"}>{transaction.type==="Depósito"?"+ ":"− "}{money.format(transaction.amount)}</b><button aria-label="Editar movimentação" onClick={()=>editTransaction(transaction)}><Pencil size={15}/></button><button aria-label="Excluir movimentação" onClick={()=>deleteTransaction(transaction)}><Trash2 size={15}/></button></div>)}{data.transactions.length===0?<p className="history-empty">Nenhuma movimentação registrada.</p>:null}</div></section>
        <section id="bets" className="panel bets-panel"><div className="panel-heading"><div><h2>Atividade recente</h2><p>{query ? `${filtered.length} resultados para “${query}”` : "Clique em uma aposta pendente para encerrá-la"}</p></div><button className="text-button" onClick={() => setQuery("")}>{query ? "Limpar busca" : `${data.bets.length} tickets`}</button></div><div className="table-wrap"><table><thead><tr><th>Evento / mercado</th><th>Entrada</th><th>Odd</th><th>Status</th><th>Resultado</th><th>Ação</th></tr></thead><tbody>{filtered.map(b => <tr key={b.id} className={b.status === "Pendente" ? "clickable-row" : ""} onClick={() => b.status === "Pendente" && setSettling(b)}><td><div className="event"><span>{b.sport.slice(0, 2).toUpperCase()}</span><div><strong>{b.event}</strong><small>{b.sport} · {b.date}</small></div></div></td><td>{money.format(b.stake)}</td><td>{b.odd.toFixed(2).replace(".", ",")}</td><td><span className={`status ${b.status.toLowerCase()}`}>{b.status}</span></td><td className={b.status === "Red" ? "negative" : b.status === "Pendente" ? "muted" : b.result >= 0 ? "positive" : "negative"}>{b.status === "Pendente" ? `${money.format(b.result)} potencial` : b.result === 0 ? money.format(0) : `${b.result > 0 ? "+ " : "− "}${money.format(Math.abs(b.result))}`}</td><td>{b.status==="Pendente"?<button className="row-action" aria-label="Excluir aposta" onClick={event=>{event.stopPropagation();deleteBet(b)}}><Trash2 size={15}/></button>:null}</td></tr>)}{filtered.length === 0 ? <tr><td colSpan={6} className="empty-row">Nenhuma aposta encontrada.</td></tr> : null}</tbody></table></div></section>
      </div>
      <footer><span>© 2026 SmartBanca</span><a id="privacy-link" href="/privacidade">Privacidade</a><button onClick={()=>setCookieChoice(null)}>Gerenciar cookies</button><span>Jogue com responsabilidade.</span></footer>
    </main>
    {modal ? <AddBetModal close={() => setModal(false)} save={addBet} /> : null}
    {transactionType ? <TransactionModal type={transactionType} close={() => setTransactionType(null)} save={addTransaction} /> : null}
    {settling ? <SettleModal bet={settling} close={() => setSettling(null)} save={settleBet} /> : null}
    {profileOpen?<ProfileModal user={user} close={()=>setProfileOpen(false)} update={setUser}/>:null}
    {toast ? <div className="toast" role="status">{toast}</div> : null}
    {!cookieChoice?<aside className="cookie-banner" aria-label="Preferências de cookies"><div><strong>Seu controle também vale para cookies.</strong><p>Usamos apenas cookies essenciais para manter sua sessão. Você pode permitir métricas anônimas quando elas forem configuradas.</p></div><div><button className="ghost-button" onClick={()=>saveCookieChoice("necessary")}>Só necessários</button><button className="primary-button" onClick={()=>saveCookieChoice("optional")}>Aceitar opcionais</button></div></aside>:null}
  </div>;
}
