"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff, KeyRound } from "lucide-react";

export function ForcePasswordChange() {
  const router=useRouter(); const[password,setPassword]=useState(""); const[confirmPassword,setConfirmPassword]=useState(""); const[show,setShow]=useState(false); const[error,setError]=useState(""); const[loading,setLoading]=useState(false);
  async function submit(event:React.FormEvent){event.preventDefault();setError("");if(password!==confirmPassword)return setError("As senhas não são iguais.");setLoading(true);const response=await fetch("/api/auth/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const body=await response.json();if(!response.ok){setError(body.error??"Use 12 caracteres, com maiúscula, minúscula e número.");setLoading(false);return;}router.refresh();}
  return <div className="mandatory-password-backdrop"><section className="mandatory-password" role="dialog" aria-modal="true" aria-labelledby="mandatory-password-title"><span><KeyRound size={24} aria-hidden="true"/></span><h1 id="mandatory-password-title">Crie sua senha pessoal</h1><p>A senha recebida era temporária. Antes de usar o SmartBanca, defina uma senha que somente você conheça.</p><form onSubmit={submit}><label>Nova senha<div className="password-field"><input value={password} onChange={event=>setPassword(event.target.value)} type={show?"text":"password"} minLength={12} maxLength={128} autoComplete="new-password" required/><button type="button" onClick={()=>setShow(value=>!value)} aria-label={show?"Ocultar senha":"Mostrar senha"}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><small>Use 12 caracteres, com letra maiúscula, minúscula e número.</small></label><label>Confirmar nova senha<input value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} type={show?"text":"password"} minLength={12} maxLength={128} autoComplete="new-password" required/></label>{error?<p className="auth-error" role="alert">{error}</p>:null}<button className="primary-button" disabled={loading}>{loading?"Salvando…":"Salvar minha senha"}</button></form></section></div>;
}
