"use client";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import Link from "next/link";

export function RecoveryForm(){
  const params=useSearchParams(); const token=params.get("token"); const verify=params.get("verify");
  const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [devUrl,setDevUrl]=useState(""); const [loading,setLoading]=useState(Boolean(verify));
  useEffect(()=>{if(!verify)return; fetch("/api/auth/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:verify})}).then(async r=>{const body=await r.json(); if(!r.ok)throw new Error(body.error); setMessage(body.message);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[verify]);
  async function requestReset(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const email=String(new FormData(event.currentTarget).get("email"));const r=await fetch("/api/auth/request-reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const body=await r.json();setLoading(false);if(!r.ok)return setError(body.error);setMessage(body.message);setDevUrl(body.devUrl??"");}
  async function reset(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const password=String(new FormData(event.currentTarget).get("password"));const r=await fetch("/api/auth/reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password})});const body=await r.json();setLoading(false);if(!r.ok)return setError(body.error);setMessage(body.message);}
  return <main className="recovery-page"><section className="recovery-card"><div className="logo"><span className="logo-mark"><i/><i/><i/></span><span>Smart<strong>Banca</strong></span></div><h1>{verify?"Confirmando seu e-mail":token?"Crie uma nova senha":"Recupere sua conta"}</h1><p>{verify?"Estamos validando o link com segurança.":token?"Use uma senha forte com 12 caracteres, maiúscula, minúscula e número.":"Informe seu e-mail. Se ele estiver cadastrado, você receberá um link válido por 30 minutos."}</p>{!verify&&!token?<form onSubmit={requestReset}><label>E-mail<input name="email" type="email" required autoComplete="email"/></label><button className="primary-button" disabled={loading}>{loading?"Enviando…":"Enviar link"}</button></form>:null}{token?<form onSubmit={reset}><label>Nova senha<input name="password" type="password" required minLength={12} autoComplete="new-password"/></label><button className="primary-button" disabled={loading}>{loading?"Salvando…":"Alterar senha"}</button></form>:null}{loading&&verify?<p>Validando…</p>:null}{message?<div className="recovery-success">{message}</div>:null}{error?<div className="auth-error">{error}</div>:null}{devUrl?<a className="dev-reset-link" href={devUrl}>Abrir link de desenvolvimento</a>:null}<Link href="/login">Voltar para o login</Link></section></main>;
}
